[package]
name = "hello_cargo"
version = "0.1.0"
authors = ["2222-42 <stephen0617@me.com>"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
